/**
 * data.js
 * Car data for Carzy web application
 * Last updated: March 18, 2025
 */

const carData = [
    {
        id: "maruti-swift",
        name: "Maruti Suzuki Swift",
        brand: "Maruti Suzuki",
        price: "₹6.00 - ₹9.10 Lakh",
        image: "maruti-swift.jpg",
        gallery: ["swift-1.jpg", "swift-2.jpg", "swift-3.jpg", "swift-4.jpg"],
        engine: "1197 cc",
        engineType: "1.2L K-Series Dual Jet Petrol Engine",
        power: "89 bhp @ 6000 rpm",
        torque: "113 Nm @ 4400 rpm",
        fuelType: "Petrol",
        transmission: "Manual/AMT",
        mileage: "23.2 kmpl",
        seating: "5 Seater",
        bodyType: "Hatchback",
        length: "3845 mm",
        width: "1735 mm",
        height: "1530 mm",
        wheelbase: "2450 mm",
        groundClearance: "163 mm",
        bootSpace: "268 liters",
        fuelTankCapacity: "37 liters",
        safetyRating: "2 Star (Global NCAP)",
        description: "The Maruti Suzuki Swift is a popular hatchback known for its sporty design, fuel efficiency, and fun-to-drive nature. The latest model comes with a 1.2L K-Series Dual Jet petrol engine that offers improved performance and fuel economy.",
        features: {
            ac: true,
            powerSteering: true,
            powerWindows: true,
            abs: true,
            airbags: "Dual Front",
            infotainment: true,
            parkingSensors: true,
            reverseCamera: true,
            sunroof: false,
            hillAssist: false
        },
        variants: [
            {name: "LXi", price: "₹6.00 Lakh", features: "Basic features, Manual AC"},
            {name: "VXi", price: "₹7.05 Lakh", features: "Power windows, Central locking"},
            {name: "ZXi", price: "₹7.92 Lakh", features: "Touchscreen, Alloy wheels"},
            {name: "ZXi+", price: "₹9.10 Lakh", features: "LED headlamps, Push button start"}
        ]
    },
    {
        id: "hyundai-i20",
        name: "Hyundai i20",
        brand: "Hyundai",
        price: "₹7.19 - ₹11.83 Lakh",
        image: "hyundai-i20.jpg",
        gallery: ["i20-1.jpg", "i20-2.jpg", "i20-3.jpg", "i20-4.jpg"],
        engine: "1197 cc",
        engineType: "1.2L Kappa Petrol Engine",
        power: "82 bhp @ 6000 rpm",
        torque: "115 Nm @ 4200 rpm",
        fuelType: "Petrol/Diesel",
        transmission: "Manual/IVT",
        mileage: "20.35 kmpl",
        seating: "5 Seater",
        bodyType: "Hatchback",
        length: "3995 mm",
        width: "1775 mm",
        height: "1505 mm",
        wheelbase: "2580 mm",
        groundClearance: "170 mm",
        bootSpace: "311 liters",
        fuelTankCapacity: "37 liters",
        safetyRating: "3 Star (Global NCAP)",
        description: "The Hyundai i20 is a premium hatchback with a stylish design, feature-rich interior, and refined driving experience. It offers multiple engine options and advanced technology features that make it a compelling choice in its segment.",
        features: {
            ac: true,
            powerSteering: true,
            powerWindows: true,
            abs: true,
            airbags: "6 Airbags",
            infotainment: true,
            parkingSensors: true,
            reverseCamera: true,
            sunroof: true,
            hillAssist: true
        },
        variants: [
            {name: "Magna", price: "₹7.19 Lakh", features: "Basic features, Manual AC"},
            {name: "Sportz", price: "₹8.57 Lakh", features: "Touchscreen, Rear AC vents"},
            {name: "Asta", price: "₹9.91 Lakh", features: "Alloy wheels, Cruise control"},
            {name: "Asta (O)", price: "₹11.83 Lakh", features: "Sunroof, 6 airbags, BOSE sound system"}
        ]
    },
    {
        id: "tata-nexon",
        name: "Tata Nexon",
        brand: "Tata Motors",
        price: "₹8.10 - ₹14.60 Lakh",
        image: "tata-nexon.jpg",
        gallery: ["nexon-1.jpg", "nexon-2.jpg", "nexon-3.jpg", "nexon-4.jpg"],
        engine: "1199 cc",
        engineType: "1.2L Turbocharged Revotron Petrol Engine",
        power: "118 bhp @ 5500 rpm",
        torque: "170 Nm @ 1750-4000 rpm",
        fuelType: "Petrol/Diesel",
        transmission: "Manual/AMT",
        mileage: "17.4 kmpl",
        seating: "5 Seater",
        bodyType: "SUV",
        length: "3993 mm",
        width: "1811 mm",
        height: "1606 mm",
        wheelbase: "2498 mm",
        groundClearance: "209 mm",
        bootSpace: "350 liters",
        fuelTankCapacity: "44 liters",
        safetyRating: "5 Star (Global NCAP)",
        description: "The Tata Nexon is a compact SUV with a distinctive design, spacious interior, and impressive safety features. It was the first Indian car to receive a 5-star safety rating from Global NCAP, making it one of the safest vehicles in its segment.",
        features: {
            ac: true,
            powerSteering: true,
            powerWindows: true,
            abs: true,
            airbags: "Dual Front",
            infotainment: true,
            parkingSensors: true,
            reverseCamera: true,
            sunroof: true,
            hillAssist: true
        },
        variants: [
            {name: "XE", price: "₹8.10 Lakh", features: "Basic features, Power windows"},
            {name: "XM", price: "₹9.54 Lakh", features: "Touchscreen, Rear AC vents"},
            {name: "XZ", price: "₹10.90 Lakh", features: "Alloy wheels, Automatic climate control"},
            {name: "XZ+", price: "₹14.60 Lakh", features: "Sunroof, Connected car features, Premium audio"}
        ]
    },
    {
        id: "honda-city",
        name: "Honda City",
        brand: "Honda",
        price: "₹11.57 - ₹15.97 Lakh",
        image: "honda-city.jpg",
        gallery: ["city-1.jpg", "city-2.jpg", "city-3.jpg", "city-4.jpg"],
        engine: "1498 cc",
        engineType: "1.5L i-VTEC Petrol Engine",
        power: "121 bhp @ 6600 rpm",
        torque: "145 Nm @ 4300 rpm",
        fuelType: "Petrol",
        transmission: "Manual/CVT",
        mileage: "18.4 kmpl",
        seating: "5 Seater",
        bodyType: "Sedan",
        length: "4549 mm",
        width: "1748 mm",
        height: "1489 mm",
        wheelbase: "2600 mm",
        groundClearance: "165 mm",
        bootSpace: "506 liters",
        fuelTankCapacity: "40 liters",
        safetyRating: "5 Star (ASEAN NCAP)",
        description: "The Honda City is a premium sedan known for its refined engine, spacious cabin, and reliable performance. It offers a perfect balance of comfort, style, and efficiency, making it a popular choice among sedan buyers.",
        features: {
            ac: true,
            powerSteering: true,
            powerWindows: true,
            abs: true,
            airbags: "6 Airbags",
            infotainment: true,
            parkingSensors: true,
            reverseCamera: true,
            sunroof: true,
            hillAssist: true
        },
        variants: [
            {name: "V", price: "₹11.57 Lakh", features: "LED headlamps, 8-inch touchscreen"},
            {name: "VX", price: "₹13.17 Lakh", features: "Sunroof, 16-inch alloy wheels"},
            {name: "ZX", price: "₹15.97 Lakh", features: "Lane watch camera, Leather seats, Connected car tech"}
        ]
    },
    {
        id: "mahindra-thar",
        name: "Mahindra Thar",
        brand: "Mahindra",
        price: "₹13.59 - ₹16.29 Lakh",
        image: "mahindra-thar.jpg",
        gallery: ["thar-1.jpg", "thar-2.jpg", "thar-3.jpg", "thar-4.jpg"],
        engine: "1997 cc",
        engineType: "2.0L mStallion Petrol Engine",
        power: "150 bhp @ 5000 rpm",
        torque: "300 Nm @ 1250-3000 rpm",
        fuelType: "Petrol/Diesel",
        transmission: "Manual/AT",
        mileage: "15.2 kmpl",
        seating: "4 Seater",
        bodyType: "SUV",
        length: "3985 mm",
        width: "1855 mm",
        height: "1920 mm",
        wheelbase: "2450 mm",
        groundClearance: "226 mm",
        bootSpace: "190 liters",
        fuelTankCapacity: "57 liters",
        safetyRating: "4 Star (Global NCAP)",
        description: "The Mahindra Thar is an iconic off-road SUV with rugged design, powerful engines, and excellent off-road capabilities. The latest generation combines these traditional strengths with modern features and improved on-road comfort.",
        features: {
            ac: true,
            powerSteering: true,
            powerWindows: true,
            abs: true,
            airbags: "Dual Front",
            infotainment: true,
            parkingSensors: true,
            reverseCamera: true,
            sunroof: false,
            hillAssist: true
        },
        variants: [
            {name: "AX Opt", price: "₹13.59 Lakh", features: "Convertible top, 16-inch wheels"},
            {name: "LX", price: "₹14.29 Lakh", features: "7-inch touchscreen, Cruise control"},
            {name: "LX AT", price: "₹16.29 Lakh", features: "Automatic transmission, Drizzle-resistant infotainment"}
        ]
    },
    {
        id: "toyota-innova",
        name: "Toyota Innova Crysta",
        brand: "Toyota",
        price: "₹19.13 - ₹25.43 Lakh",
        image: "toyota-innova.jpg",
        gallery: ["innova-1.jpg", "innova-2.jpg", "innova-3.jpg", "innova-4.jpg"],
        engine: "2694 cc",
        engineType: "2.7L Petrol Engine",
        power: "164 bhp @ 5200 rpm",
        torque: "245 Nm @ 4000 rpm",
        fuelType: "Diesel",
        transmission: "Manual/AT",
        mileage: "13.9 kmpl",
        seating: "7/8 Seater",
        bodyType: "MUV",
        length: "4735 mm",
        width: "1830 mm",
        height: "1795 mm",
        wheelbase: "2750 mm",
        groundClearance: "176 mm",
        bootSpace: "300 liters",
        fuelTankCapacity: "55 liters",
        safetyRating: "5 Star (ASEAN NCAP)",
        description: "The Toyota Innova Crysta is a premium MPV known for its comfortable ride, spacious cabin, and legendary reliability. It offers versatile seating configurations, powerful engines, and a host of comfort features, making it ideal for family travel.",
        features: {
            ac: true,
            powerSteering: true,
            powerWindows: true,
            abs: true,
            airbags: "7 Airbags",
            infotainment: true,
            parkingSensors: true,
            reverseCamera: true,
            sunroof: false,
            hillAssist: true
        },
        variants: [
            {name: "GX", price: "₹19.13 Lakh", features: "8-inch touchscreen, Cruise control"},
            {name: "VX", price: "₹22.60 Lakh", features: "Leather seats, Ambient lighting"},
            {name: "ZX", price: "₹25.43 Lakh", features: "Captain seats, Premium audio, Auto headlamps"}
        ]
    },
    {
        id: "kia-seltos",
        name: "Kia Seltos",
        brand: "Kia",
        price: "₹10.49 - ₹18.65 Lakh",
        image: "kia-seltos.jpg",
        gallery: ["seltos-1.jpg", "seltos-2.jpg", "seltos-3.jpg", "seltos-4.jpg"],
        engine: "1497 cc",
        engineType: "1.5L Petrol Engine",
        power: "113 bhp @ 6300 rpm",
        torque: "144 Nm @ 4500 rpm",
        fuelType: "Petrol/Diesel",
        transmission: "Manual/IVT/DCT",
        mileage: "16.8 kmpl",
        seating: "5 Seater",
        bodyType: "SUV",
        length: "4315 mm",
        width: "1800 mm",
        height: "1645 mm",
        wheelbase: "2610 mm",
        groundClearance: "190 mm",
        bootSpace: "433 liters",
        fuelTankCapacity: "50 liters",
        safetyRating: "3 Star (Global NCAP)",
        description: "The Kia Seltos is a feature-rich compact SUV with striking design, multiple powertrain options, and advanced technology features. It offers a premium cabin experience with high-quality materials and a host of convenience features.",
        features: {
            ac: true,
            powerSteering: true,
            powerWindows: true,
            abs: true,
            airbags: "6 Airbags",
            infotainment: true,
            parkingSensors: true,
            reverseCamera: true,
            sunroof: true,
            hillAssist: true
        },
        variants: [
            {name: "HTE", price: "₹10.49 Lakh", features: "Basic features, LED headlamps"},
            {name: "HTK+", price: "₹12.79 Lakh", features: "10.25-inch touchscreen, Cruise control"},
            {name: "GTX+", price: "₹18.65 Lakh", features: "Panoramic sunroof, BOSE sound system, 360° camera"}
        ]
    },
    {
        id: "mg-hector",
        name: "MG Hector",
        brand: "MG",
        price: "₹14.73 - ₹21.73 Lakh",
        image: "mg-hector.jpg",
        gallery: ["hector-1.jpg", "hector-2.jpg", "hector-3.jpg", "hector-4.jpg"],
        engine: "1451 cc",
        engineType: "1.5L Turbocharged Petrol Engine",
        power: "141 bhp @ 5000 rpm",
        torque: "250 Nm @ 1600-3600 rpm",
        fuelType: "Petrol/Diesel",
        transmission: "Manual/DCT/CVT",
        mileage: "15.8 kmpl",
        seating: "5 Seater",
        bodyType: "SUV",
        length: "4655 mm",
        width: "1835 mm",
        height: "1760 mm",
        wheelbase: "2750 mm",
        groundClearance: "192 mm",
        bootSpace: "587 liters",
        fuelTankCapacity: "60 liters",
        safetyRating: "5 Star (BNCAP)",
        description: "The MG Hector is a tech-loaded SUV with a spacious cabin, large touchscreen, and connected car features. It's known for its 'Internet Inside' capabilities, allowing users to control various vehicle functions through voice commands and a smartphone app.",
        features: {
            ac: true,
            powerSteering: true,
            powerWindows: true,
            abs: true,
            airbags: "6 Airbags",
            infotainment: true,
            parkingSensors: true,
            reverseCamera: true,
            sunroof: true,
            hillAssist: true
        },
        variants: [
            {name: "Style", price: "₹14.73 Lakh", features: "LED headlamps, 10.4-inch touchscreen"},
            {name: "Smart", price: "₹16.20 Lakh", features: "Connected car tech, 17-inch alloys"},
            {name: "Sharp Pro", price: "₹21.73 Lakh", features: "Panoramic sunroof, ADAS, 360° camera"}
        ]
    }
];
